In [ ]:
import pandas as pd

In [3]:
base_case_opt_results = pd.read_csv("../outputs/policy_results/base_case_optimization_results.csv")
base_case_opt_results

,family,policy_type,safety_stock,reorder_point,order_quantity,order_up_to_level,fill_rate,cycle_service_level,total_cost,avg_inventory,num_orders,units_short,gamma_benchmark_safety_stock
0,GROCERY I,"(s,Q)",487622.562927,1.750781e+06,314433.578236,NaN,0.991579,0.931267,543439.884926,609857.946773,3.0,36107.045287,486101.043089
1,BEVERAGES,"(s,Q)",588068.725480,1.565681e+06,260348.018483,NaN,0.996574,0.984700,156552.765627,687134.048563,3.0,12874.637348,691113.626070
2,CLEANING,"(R,S)",0.000000,NaN,NaN,798371.817225,1.000000,1.000000,1361.653599,446039.914304,3.0,0.000000,83818.182746

In [5]:
final_policy_results = pd.read_csv("../outputs/policy_results/final_policy_results.csv")
final_policy_results

,family,policy_type,safety_stock,reorder_point,order_quantity,order_up_to_level,fill_rate,cycle_service_level,total_cost,avg_inventory,num_orders,units_short,gamma_benchmark_safety_stock
0,GROCERY I,"(s,Q)",487622.562927,1.750781e+06,314433.578236,NaN,0.991579,0.931267,543439.884926,609857.946773,3.0,36107.045287,486101.043089
1,BEVERAGES,"(s,Q)",588068.725480,1.565681e+06,260348.018483,NaN,0.996574,0.984700,156552.765627,687134.048563,3.0,12874.637348,691113.626070
2,CLEANING,"(R,S)",0.000000,NaN,NaN,798371.817225,1.000000,1.000000,1361.653599,446039.914304,3.0,0.000000,83818.182746

In [6]:
sensitivity_summary = pd.read_csv("../outputs/sensitivity_results/sensitivity_summary.csv")
sensitivity_summary

,policy_type,safety_stock,reorder_point,order_quantity,order_up_to_level,fill_rate,cycle_service_level,total_cost,avg_inventory,num_orders,units_short,family,scenario,holding_rate_annual,order_cost_K,shortage_cost_B,target_fill_rate,lead_time,review_period
0,"(s,Q)",4.876226e+05,1.750781e+06,314433.578236,NaN,0.991579,0.931267,543439.884926,6.098579e+05,3.0,36107.045287,GROCERY I,Base Case,0.15,25.0,15.0,0.95,1,1
1,"(s,Q)",4.876226e+05,1.750781e+06,317141.927807,NaN,0.991950,0.934300,520291.186196,6.133582e+05,3.0,34602.443409,GROCERY I,Holding Rate 10%,0.10,25.0,15.0,0.95,1,1
2,"(s,Q)",4.876226e+05,1.750781e+06,236395.696446,NaN,0.989361,0.914567,679028.765270,5.876484e+05,3.0,45075.235490,GROCERY I,Holding Rate 25%,0.25,25.0,15.0,0.95,1,1
3,"(s,Q)",4.876226e+05,1.750781e+06,193016.277894,NaN,0.988042,0.905367,755866.256378,5.786262e+05,3.0,50277.809490,GROCERY I,Order Cost K=10,0.15,10.0,15.0,0.95,1,1
4,"(s,Q)",4.876226e+05,1.750781e+06,444676.230806,NaN,0.995019,0.961400,334013.394360,6.528222e+05,3.0,22132.016894,GROCERY I,Order Cost K=50,0.15,50.0,15.0,0.95,1,1
5,"(s,Q)",4.876226e+05,1.750781e+06,314433.578236,NaN,0.991579,0.931267,272637.045271,6.098579e+05,3.0,36107.045287,GROCERY I,Shortage Cost 50%,0.15,25.0,7.5,0.95,1,1
6,"(s,Q)",4.876226e+05,1.750781e+06,314433.578236,NaN,0.991579,0.931267,814242.724581,6.098579e+05,3.0,36107.045287,GROCERY I,Shortage Cost 150%,0.15,25.0,22.5,0.95,1,1
7,"(s,Q)",5.880687e+05,1.565681e+06,260348.018483,NaN,0.996574,0.984700,156552.765627,6.871340e+05,3.0,12874.637348,BEVERAGES,Base Case,0.15,25.0,12.0,0.95,1,1
8,"(s,Q)",5.880687e+05,1.565681e+06,259073.669086,NaN,0.996583,0.985000,155284.034558,6.867956e+05,3.0,12824.022819,BEVERAGES,Holding Rate 10%,0.10,25.0,12.0,0.95,1,1
9,"(s,Q)",5.880687e+05,1.565681e+06,207966.730084,NaN,0.996098,0.982500,177634.224837,6.643550e+05,3.0,14530.434212,BEVERAGES,Holding Rate 25%,0.25,25.0,12.0,0.95,1,1
10,"(s,Q)",5.880687e+05,1.565681e+06,169804.124060,NaN,0.995786,0.981067,189512.998534,6.518729e+05,3.0,15633.549650,BEVERAGES,Order Cost K=10,0.15,10.0,12.0,0.95,1,1
11,"(s,Q)",5.880687e+05,1.565681e+06,391199.429842,NaN,0.997382,0.988533,121149.853153,7.392849e+05,3.0,9905.608382,BEVERAGES,Order Cost K=50,0.15,50.0,12.0,0.95,1,1
12,"(s,Q)",5.880687e+05,1.565681e+06,260348.018483,NaN,0.996574,0.984700,79304.941537,6.871340e+05,3.0,12874.637348,BEVERAGES,Shortage Cost 50%,0.15,25.0,6.0,0.95,1,1
13,"(s,Q)",5.880687e+05,1.565681e+06,260348.018483,NaN,0.996574,0.984700,233800.589716,6.871340e+05,3.0,12874.637348,BEVERAGES,Shortage Cost 150%,0.15,25.0,18.0,0.95,1,1
14,"(R,S)",0.000000e+00,NaN,NaN,7.983718e+05,1.000000,1.000000,1361.653599,4.460399e+05,3.0,0.000000,CLEANING,Base Case,0.15,25.0,15.0,0.95,1,1
15,"(R,S)",0.000000e+00,NaN,NaN,7.983718e+05,1.000000,1.000000,932.769066,4.460399e+05,3.0,0.000000,CLEANING,Holding Rate 10%,0.10,25.0,15.0,0.95,1,1
16,"(R,S)",0.000000e+00,NaN,NaN,7.983718e+05,1.000000,1.000000,2219.422665,4.460399e+05,3.0,0.000000,CLEANING,Holding Rate 25%,0.25,25.0,15.0,0.95,1,1
17,"(R,S)",0.000000e+00,NaN,NaN,7.983718e+05,1.000000,1.000000,1316.653599,4.460399e+05,3.0,0.000000,CLEANING,Order Cost K=10,0.15,10.0,15.0,0.95,1,1
18,"(R,S)",0.000000e+00,NaN,NaN,7.983718e+05,1.000000,1.000000,1436.653599,4.460399e+05,3.0,0.000000,CLEANING,Order Cost K=50,0.15,50.0,15.0,0.95,1,1
19,"(R,S)",0.000000e+00,NaN,NaN,7.983718e+05,1.000000,1.000000,1361.653599,4.460399e+05,3.0,0.000000,CLEANING,Shortage Cost 50%,0.15,25.0,7.5,0.95,1,1
20,"(R,S)",0.000000e+00,NaN,NaN,7.983718e+05,1.000000,1.000000,1361.653599,4.460399e+05,3.0,0.000000,CLEANING,Shortage Cost 150%,0.15,25.0,22.5,0.95,1,1
21,"(s,Q)",4.876226e+05,1.750781e+06,314433.578236,NaN,0.991579,0.931267,543439.884926,6.098579e+05,3.0,36107.045287,GROCERY I,Service Target beta=0.90,0.15,25.0,15.0,0.90,1,1
22,"(s,Q)",4.876226e+05,1.750781e+06,314433.578236,NaN,0.991579,0.931267,543439.884926,6.098579e+05,3.0,36107.045287,GROCERY I,Service Target beta=0.95,0.15,25.0,15.0,0.95,1,1
23,"(s,Q)",4.876226e+05,1.750781e+06,314433.578236,NaN,0.991579,0.931267,543439.884926,6.098579e+05,3.0,36107.045287,GROCERY I,Service Target beta=0.98,0.15,25.0,15.0,0.98,1,1
24,"(s,Q)",5.880687e+05,1.565681e+06,260348.018483,NaN,0.996574,0.984700,156552.765627,6.871340e+05,3.0,12874.637348,BEVERAGES,Service Target beta=0.90,0.15,25.0,12.0,0.90,1,1
25,"(s,Q)",5.880687e+05,1.565681e+06,260348.018483,NaN,0.996574,0.984700,156552.765627,6.871340e+05,3.0,12874.637348,BEVERAGES,Service Target beta=0.95,0.15,25.0,12.0,0.95,1,1
26,"(s,Q)",5.880687e+05,1.565681e+06,260348.018483,NaN,0.996574,0.984700,156552.765627,6.871340e+05,3.0,12874.637348,BEVERAGES,Service Target beta=0.98,0.15,25.0,12.0,0.98,1,1
27,"(R,S)",0.000000e+00,NaN,NaN,7.983718e+05,1.000000,1.000000,1361.653599,4.460399e+05,3.0,0.000000,CLEANING,Service Target beta=0.90,0.15,25.0,15.0,0.90,1,1
28,"(R,S)",0.000000e+00,NaN,NaN,7.983718e+05,1.000000,1.000000,1361.653599,4.460399e+05,3.0,0.000000,CLEANING,Service Target beta=0.95,0.15,25.0,15.0,0.95,1,1
29,"(R,S)",0.000000e+00,NaN,NaN,7.983718e+05,1.000000,1.000000,1361.653599,4.460399e+05,3.0,0.000000,CLEANING,Service Target beta=0.98,0.15,25.0,15.0,0.98,1,1
30,"(s,Q)",4.876226e+05,1.750781e+06,314433.578236,NaN,0.991579,0.931267,543439.884926,6.098579e+05,3.0,36107.045287,GROCERY I,Lead Time L=1,0.15,25.0,15.0,0.95,1,1
31,"(s,Q)",9.494687e+05,3.475786e+06,295937.485398,NaN,0.998816,0.991967,87153.083474,1.312314e+06,3.0,5552.837483,GROCERY I,Lead Time L=2,0.15,25.0,15.0,0.95,2,1
32,"(s,Q)",5.880687e+05,1.565681e+06,260348.018483,NaN,0.996574,0.984700,156552.765627,6.871340e+05,3.0,12874.637348,BEVERAGES,Lead Time L=1,0.15,25.0,12.0,0.95,1,1
33,"(s,Q)",1.060753e+06,3.015977e+06,260348.018483,NaN,0.999300,0.994633,37522.098981,1.353301e+06,3.0,2795.278922,BEVERAGES,Lead Time L=2,0.15,25.0,12.0,0.95,2,1
34,"(R,S)",0.000000e+00,NaN,NaN,7.983718e+05,1.000000,1.000000,1361.653599,4.460399e+05,3.0,0.000000,CLEANING,"Lead Time L=1, R=1",0.15,25.0,15.0,0.95,1,1
35,"(R,S)",0.000000e+00,NaN,NaN,1.056996e+06,0.999999,0.999967,1360.334541,4.385408e+05,3.0,1.354206,CLEANING,"Lead Time L=2, R=1",0.15,25.0,15.0,0.95,2,1
36,"(R,S)",0.000000e+00,NaN,NaN,1.056996e+06,0.999999,0.999967,1360.334541,4.385408e+05,3.0,1.354206,CLEANING,"Lead Time L=2, R=2",0.15,25.0,15.0,0.95,2,2
37,"(s,Q)",4.876226e+05,1.750781e+06,314433.578236,NaN,0.991579,0.931267,543439.884926,6.098579e+05,3.0,36107.045287,GROCERY I,Uncertainty: Ratio Bootstrap,0.15,25.0,15.0,0.95,1,1
38,"(s,Q)",6.372488e+05,1.899179e+06,314280.665139,NaN,0.997825,0.981000,141839.398687,7.527999e+05,3.0,9306.190704,GROCERY I,Uncertainty: Residual Bootstrap,0.15,25.0,15.0,0.95,1,1
39,"(s,Q)",5.061513e+05,1.767962e+06,314265.725476,NaN,0.992400,0.936933,488612.495169,6.257792e+05,3.0,32448.824185,GROCERY I,Uncertainty: Ratio KDE,0.15,25.0,15.0,0.95,1,1
40,"(s,Q)",6.022256e+05,1.580018e+06,260372.066735,NaN,0.996456,0.984667,162954.393842,7.010712e+05,3.0,13404.756092,BEVERAGES,Uncertainty: Ratio Bootstrap,0.15,25.0,12.0,0.95,1,1
41,"(s,Q)",5.682882e+05,1.548529e+06,276991.384306,NaN,0.999173,0.990067,35421.384014,6.668733e+05,3.0,2785.225930,BEVERAGES,Uncertainty: Residual Bootstrap,0.15,25.0,12.0,0.95,1,1
42,"(s,Q)",6.448203e+05,1.623690e+06,268656.483547,NaN,0.996605,0.985967,158065.252112,7.424856e+05,3.0,12987.372221,BEVERAGES,Uncertainty: Ratio KDE,0.15,25.0,12.0,0.95,1,1
43,"(R,S)",0.000000e+00,NaN,NaN,7.982155e+05,1.000000,1.000000,1361.362216,4.459389e+05,3.0,0.000000,CLEANING,Uncertainty: Ratio Bootstrap,0.15,25.0,15.0,0.95,1,1
44,"(R,S)",0.000000e+00,NaN,NaN,7.984815e+05,1.000000,1.000000,1361.348242,4.459341e+05,3.0,0.000000,CLEANING,Uncertainty: Residual Bootstrap,0.15,25.0,15.0,0.95,1,1
45,"(R,S)",0.000000e+00,NaN,NaN,7.979472e+05,1.000000,1.000000,1360.320662,4.455778e+05,3.0,0.000000,CLEANING,Uncertainty: Ratio KDE,0.15,25.0,15.0,0.95,1,1

![sensitivity_cost_summary_grocery_i](../outputs/plots/sensitivity_cost_summary_grocery_i.png)

![sensitivity_cost_summary_grocery_i](../outputs/plots/sensitivity_cost_summary_beverages.png)

![sensitivity_cost_summary_grocery_i](../outputs/plots/sensitivity_cost_summary_cleaning.png)

In [8]:
policy_justfication_statistics = pd.read_csv("../outputs/tables/policy_justification_statistics.csv")
policy_justfication_statistics

,family,Mean Weekly Demand,Weekly Standard Deviation,Weekly CV,Weekly Demand Frequency,Weekly Zero-Demand Frequency,Chosen Policy
0,BEVERAGES,9.461241e+05,381694.896193,0.403430,1.0,0.0,SQ
1,CLEANING,4.155624e+05,73498.654089,0.176865,1.0,0.0,RS
2,GROCERY I,1.476838e+06,333585.520786,0.225878,1.0,0.0,SQ

In [9]:
powerbi_inventory_policy_table = pd.read_csv("../outputs/tables/powerbi_inventory_policy_table.csv")
powerbi_inventory_policy_table

,family,policy_type,lead_time,review_period,risk_period,safety_stock,reorder_point,order_quantity,order_up_to_level,fill_rate,cycle_service_level,total_cost,avg_inventory,num_orders,units_short
0,GROCERY I,"(s,Q)",1,NaN,1,487622.5629,1.750781e+06,314433.5782,NaN,0.9916,0.9313,543439.8849,609857.9468,3.0,36107.0453
1,BEVERAGES,"(s,Q)",1,NaN,1,588068.7255,1.565681e+06,260348.0185,NaN,0.9966,0.9847,156552.7656,687134.0486,3.0,12874.6373
2,CLEANING,"(R,S)",1,1.0,2,0.0000,NaN,NaN,798371.8172,1.0000,1.0000,1361.6536,446039.9143,3.0,0.0000

![sensitivity_cost_summary_grocery_i](../outputs/plots/ending_inventory_dist_grocery_i.png)

![sensitivity_cost_summary_grocery_i](../outputs/plots/ending_inventory_dist_beverages.png)

![sensitivity_cost_summary_grocery_i](../outputs/plots/ending_inventory_dist_cleaning.png)